name: Deploy to DigitalOcean 

on:
  push:
    branches:
    - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Copy files to Droplet
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/var/www/soundwave"

    - name: Execute remote commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/soundwave
          # autre commandes à venir
