name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - production  # Déclenche le workflow sur chaque push vers la branche 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to Droplet
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} "rm -rf /var/www/soundwave && mkdir -p /var/www/soundwave"
        scp -r ./* root@${{ secrets.DROPLET_IP }}:/var/www/soundwave

    - name: Execute remote commands
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << 'EOF'
          cd /var/www/soundwave

